### ISSUE TITLE
rest-client dependency is missing on CI platforms

### ISSUE THREAD

**Issue by bobmaerten** [codacy/ruby-codacy-coverage#1]
Hi!

Sad to be the first to report a problem on this gem, but when I setup this gem to report code-coverage, the platform we usually solicit report missing depandency.

Codeship:
<img width="938" alt="upgrade_config___add_codacy_along_codeclimate_for_code_analysis_ _levups_sauron_ _codeship" src="https://cloud.githubusercontent.com/assets/907274/10242650/a74e575c-68f2-11e5-8626-979b3623f42b.png">

CircleCI:
<img width="857" alt="levups_sauron__49_-_circleci" src="https://cloud.githubusercontent.com/assets/907274/10242671/c71f180a-68f2-11e5-84db-28fb911e5f00.png">

When I add rest-client to my Gemfile, tests are fine again.

**Comment by naps62** [comment]
Just noticed this issue as well. Wouldn't this be worth bumping the version and publishing to rubygems?

**Comment by bobmaerten** [comment]
Indeed, pushing to rubygems would be appreciated!

**Comment by mrfyda** [comment]
Published as 0.2.0

Thanks @bobmaerten and @naps62 for reporting, and sorry about the delay publishing it.
