### ISSUE TITLE
cannot load rest_client

### ISSUE THREAD

**Issue by andrebras** [codacy/ruby-codacy-coverage#13]
Hi,

https://github.com/codacy/ruby-codacy-coverage/compare/0.1.0...andrebras:0.1.1

Tag 0.1.0 doesn't add rest-client as a runtime dependency. When adding the lines below to your rails_helper.rb or spec_helper.rb:

```
require 'codacy-coverage'
Codacy::Reporter.start
```

fails while running specs.

```
cannot load such file -- rest_client (LoadError)
```

Cheers.

**Comment by machadoit** [comment]
Hi @andrebras,

I created a ticket to review this issue, the fix you made in your fork solves the problem?
We do accept pull request if you want to contribute =)

**Comment by machadoit** [comment]
The new release https://github.com/codacy/ruby-codacy-coverage/releases/tag/1.0.0 will hopefully fit your needs =)
