### ISSUE TITLE
Do not prevent simplecov reports on localhost

### ISSUE THREAD

**Issue by darrenleeweber** [codacy/ruby-codacy-coverage#27]
Note how coveralls provides an option to support their formatter and simplecov, see
- https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails
- scroll down to the section on `SimpleCov Customization`
- sorry, not sure how or where this is implemented

**Comment by rtfpessoa** [comment]
@darrenleeweber `export CODACY_RUN_LOCAL=true`

**Comment by darrenleeweber** [comment]
A possible work-around is something like the following:

```
# rspec/spec_helper.rb
require 'simplecov'
SimpleCov.profiles.define 'sc_profile' do
  add_filter '.gems'
  add_filter 'pkg'
  add_filter 'spec'
  add_filter 'vendor'
end

if ENV['CODACY_PROJECT_TOKEN']
  require 'codacy-coverage'
  Codacy::Reporter.start
else
  SimpleCov.start 'dpn-sync'
end
```
However, this may not apply the simplecov profile defined to the codacy coverage report.  It does allow Simplecov to run locally and codacy to run when the env value is set.

**Comment by darrenleeweber** [comment]
Please elaborate on the function of `export CODACY_RUN_LOCAL=true` (in the README).  It seems to be in the enterprise section of the README and I don't understand whether it lets simplecov output results to ./coverage and whether it interferes with a simplecov profile.

**Comment by darrenleeweber** [comment]
Just tested using `export CODACY_RUN_LOCAL=true` and it does interfere with simplecov output to ./coverage.  It seems to just enable codacy reporting to work as usual.

**Comment by rtfpessoa** [comment]
Without defining CODACY_RUN_LOCAL locally, coverage will not be sent.

Maybe I did not understand your problem. Regarding the options you can do something similar with:

```
require 'simplecov'
require 'codacy-coverage'

SimpleCov.formatter = Codacy::Formatter
SimpleCov.start do
  add_filter 'app/secrets'
end
```

**Comment by darrenleeweber** [comment]
Using the `Codacy::Formatter`, as above, there is no simplecov output in `./coverage`.  That output is important for immediate feedback and any offline coverage reporting.  The workaround noted above is working locally (although not yet tested on a github push and travis build, where it should push the coverage report to codacy because the ENV is defined on travis builds).

**Comment by darrenleeweber** [comment]
Another option might be to use multiple formatters, as in
```
#spec/spec_helper.rb

SimpleCov::Formatter::MultiFormatter[
  SimpleCov::Formatter::HTMLFormatter,
  Coveralls::SimpleCov::Formatter
]
````

**Comment by darrenleeweber** [comment]
Yes, the following workaround worked:
```ruby
#spec/spec_helper.rb
require 'simplecov'
require 'codacy-coverage'
SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new(
  [
    SimpleCov::Formatter::HTMLFormatter,
    Codacy::Formatter
  ]
)
SimpleCov.start do
  add_filter '.gems'
  add_filter 'pkg'
  add_filter 'spec'
  add_filter 'vendor'
end
```

**Comment by darrenleeweber** [comment]
The multi-formatter solution ^^ worked locally and on a travis.ci build
- https://travis-ci.org/dpn-admin/dpn-sync/builds/180872271

That could resolve this issue, although it would be great to note this in the README (then close this issue)?

**Comment by rtfpessoa** [comment]
Added. Thanks for the help.
