### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by msdundar** [codacy/ruby-codacy-coverage#37]
Hi,

I noticed an update on this GEM from 1.1.8 to 2.0.1. It seems like a major change according to your version numbering.

Can you please share a CHANGELOG if we need to change anything in any way, after the upgrade?

Thanks.

**Comment by rtfpessoa** [comment]
Hi @msdundar sorry for the bad release notes.
Seems like I forgot to state the fact that we dropped support for Ruby <2.
For that reason I bumped a major since it might break some people using older versions.

Notes fixed. Thanks for the feedback.
