### ISSUE TITLE
coverage badge

### ISSUE THREAD

**Issue by AstmDesign** [codacy/ruby-codacy-coverage#41]
Hello guys,
After followed the steps it's created to me folder called coverage contains the files 
.last_run.json
.resultset.json
.resultset.json.lock
so how I can now showing the coverage percentage as badge image after that?!

**Comment by rtfpessoa** [comment]
@AstmDesign, if you posted the coverage correctly to Codacy you should have the badge inside your project settings, those files might just be generated by rspec during the process.

If you have doubts about it please reach out support through the in app chat or email to `support at codacy dot com`.

**Comment by AstmDesign** [comment]
Hi @rtfpessoa, Actually I contacted with Codacy support.
Thank you
