### ISSUE TITLE
gem 0.2.2 does not include fix for stripping carriage returns

### ISSUE THREAD

**Issue by vaneyckt** [codacy/ruby-codacy-coverage#5]
Hi there,

gem 0.2.2 does not include [this fix](https://github.com/codacy/ruby-codacy-coverage/blob/master/lib/codacy/git.rb#L21). Any chance of getting this updated?

It might also be a good idea to start adding tags to the repo, so it's easier to confirm which code is in a particular gem version. Would save me the time of having to unpack it :).

**Comment by nmatpt** [comment]
Issue should be fixed in the [0.2.3](https://rubygems.org/gems/codacy-coverage/versions/0.2.3) gem. We just started tagging the commits, thanks for the tip ;)
